# Generated by Django 4.1.2 on 2022-11-11 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='AdvHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименовение рубрики')),
            ],
        ),
        migrations.CreateModel(
            name='AdvStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип объявления')),
            ],
        ),
        migrations.CreateModel(
            name='AdvType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип объявления')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1500, verbose_name='заголовок')),
                ('description', models.TextField(default='default text', max_length=3000, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicated_at', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('publicated_end_at', models.DateTimeField(auto_now=True, verbose_name='дата окончания публикации')),
                ('price', models.FloatField(default=0.0, verbose_name='цена')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_author', to='advertisements_app.advauthor')),
                ('heading', models.ForeignKey(default='Work', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_heading', to='advertisements_app.advheading')),
                ('type', models.ForeignKey(choices=[('BU', 'Buy'), ('SE', 'Sell'), ('RE', 'Rent')], default='Buy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_type', to='advertisements_app.advtype')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
