# Generated by Django 4.1.2 on 2022-11-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='type',
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип объявления'),
        ),
    ]
