# Generated by Django 4.1.2 on 2022-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvStatus',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.CharField(choices=[('UN', 'Unknown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='heading',
            field=models.CharField(choices=[('WO', 'Work'), ('SP', 'Sport'), ('CA', 'Cars')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('BU', 'Buy'), ('SE', 'Sell'), ('RE', 'Rent')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AdvAuthor',
        ),
        migrations.DeleteModel(
            name='AdvHeading',
        ),
        migrations.DeleteModel(
            name='AdvType',
        ),
    ]
