# Generated by Django 4.1.2 on 2022-11-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0003_advertisement_status_advertisement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='status',
        ),
    ]
