# Generated by Django 4.1.2 on 2022-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_users', '0002_profile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Группа'),
        ),
    ]
