# Generated by Django 4.1.2 on 2022-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_users', '0003_profile_user_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile2',
            options={'permissions': (('view_kpi', 'Может просматривать kpi'), ('view_alarms', 'Может просматривать alarms')), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.ManyToManyField(to='auth.group', verbose_name='Группа'),
        ),
    ]
