# Generated by Django 4.1.2 on 2022-11-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=400, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=5000, verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('text', models.CharField(default='', max_length=500, verbose_name='текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text2', models.CharField(default='', max_length=500, verbose_name='текст комментария2')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.news')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
