# Generated by Django 4.1.2 on 2022-11-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newsdetail_alter_news_options_news_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsDetail',
        ),
    ]
