# Generated by Django 4.1.2 on 2022-11-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_delete_newsdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
    ]
