# Generated by Django 4.1.2 on 2022-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=400, verbose_name='Заголовок'),
        ),
    ]
