# Generated by Django 4.1.2 on 2022-11-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_comment_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
