# Generated by Django 4.1.2 on 2022-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_newstags_delete_tags_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='newstags',
            old_name='text',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='newstags',
            name='news',
            field=models.ManyToManyField(to='app_news.news'),
        ),
    ]
