# Generated by Django 4.1.2 on 2022-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstags',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
